#33 バックエンド 獣害情報一覧を表示できるようにコントローラーを修正する
gunsow911/ono_hackathon_saru pull request #34
Opened 2023-04-16 07:49 UTC by greenthinktank

#関連issue
closed #33 

#概要
pagenation（１ページに２０づつ取得する）という形にコントローラーを変更しました。

お手数ですが、レビューいただければありがたいです。

2023-04-18 09:44 UTC, gunsow911 requested changes
@greenthinktank 
レビューしました！お願いします！

2023-04-18 09:44 UTC, gunsow911 commented on api/app/Http/Controllers/Console/MatterController.php
> +        $list->with([
withはEagerLoadを行うために設定するものです。
EagerLoadは、**リレーションがある場合**、予め一度に取っておくというロード方法です。
よって、Matterモデルのプロパティである、'userId', 'location'...などはロードする必要はありません。
withに書くのは、リレーション名のみになります。

2023-04-18 09:47 UTC, gunsow911 commented on api/app/Models/Matter.php
> +    public function location()
データベースのカラムに相当する部分はリレーションを定義する必要はありません。

2023-04-18 09:53 UTC, gunsow911 commented on api/app/UseCases/Matter/ListAction.php
> +        ->matters()
mattersって関数ありましたっけ…？

2023-04-18 09:53 UTC, gunsow911 commented on api/app/UseCases/Matter/ListAction.php
> +    // 全部のデータを取得すると多すぎて見にくいし、処理が重くなる原因になるので、取得するデータを制限して取得する（N＋１問題も避けるためにeager loadingする）
EagerLoadはアクション内ですべきではありません。
なぜならば、どのリレーションデータを取得するか？は、アクション内では判断できないからです。

EagerLoadはControllerで行うことになります。
(と言ってもここでEagerLoadはしていないですが…)

2023-04-18 09:53 UTC, gunsow911 commented on api/app/UseCases/Matter/ListAction.php
> +        ->get();
ここでgetを行うとクエリが実行されてしまいます。
全件取得してしまうので、クエリ(Builder)のままで返却するべきです。

2023-04-18 09:59 UTC, gunsow911 commented on api/app/Http/Controllers/MatterController.php
> +        return MatterResource::collection($list->paginate(20));
ちょっとややこしいですが、管理者コンソールではない通常の獣害情報一覧にはページネーションはいりません。
ここは、地図に表示させるためのヒートマップに使うので、できる限り一度に表示させたいという意図があります。
(とはいえ、際限なく取得するのもアレなので、何らかの対応が必要ですが…)

2023-04-18 10:04 UTC, gunsow911 commented on api/tests/Feature/Http/Controllers/MatterControllerTest.php
> +        // policyができれば、ここにmockpolicyが入ることになる？
はい、おっしゃるとおり、ポリシーを利用する場合、ここでポリシーを騙すためのmockPolicyが入ります。
ただ、現段階では複雑な権限はないので、Policyを導入する予定はありません。

2023-04-22 05:07 UTC, greenthinktank commented
@gunsow911 
大変遅くなりました。一応、何とか全体テストを通過するようにコードを書いて見ました。
これでできているような気はしますが、何とも言えない感じです。
レビューいただければありがたいです。よろしくお願いいたします！

2023-04-22 05:17 UTC, gunsow911 commented on api/tests/Feature/Http/Controllers/MatterControllerTest.php
> +        $this->instance(ListAction::class, $action);
この書き方いいですね！
mockAction廃止でも良さそうです！

2023-04-22 05:26 UTC, gunsow911 commented on api/tests/Feature/Http/Controllers/MatterControllerTest.php
> +        $action->shouldReceive('__invoke')
ここ注意です。
__invokeの戻り値は、Matterの配列ではなく、**Matterのクエリ**です。
ちょっと書き換えますね。

2023-04-22 05:32 UTC, gunsow911 commented on api/tests/Feature/Http/Controllers/MatterControllerTest.php
> +        $this->instance(ListAction::class, $action);
すみません、よく検討するとこの方法では難しいですね。
戻り値の状態についてMockしたいのでListActionについてMockするとうまくいきませんね…

2023-04-22 05:37 UTC, gunsow911 commented on api/tests/Feature/Http/Controllers/MatterControllerTest.php
> +        $this->instance(ListAction::class, $action);
ActionをMockするのではなく(これはmockActionでできています)、**Actionの戻り値をMockする**感じですね。

2023-04-22 05:45 UTC, gunsow911 approved these changes

2023-04-22 06:03 UTC, greenthinktank commented
@gunsow911 
getとかbuilderは修正いただいたところに必要なんですね、、、ありがとうございます。
マージさせていただきます！

2023-04-22 06:03 UTC, merged